### ISSUE TITLE
databricks.repo property vs bucketName property?

### ISSUE THREAD

**Issue by samshuster** [edmunds/databricks-maven-plugin#15]
Currently it is unclear where databricks.repo should be set vs bucketName.

Should the properties be merged?

**Comment by daragallagher** [comment]
This inconsistency is causing me problems.  But I may be misunderstanding something.

(Btw - even the README is inconsistent here - the example given suggests setting databricks.repo - a maven project property - to "bucketname/artifacts" but also suggests that bucketName - a plugin configuration property - be set to ${databricks.repo}.

As an aside,  I don't think the plugin should use project properties for it's configuration at all unless they are standard maven properties like "encoding" which are used by many plugins.  Users always have the option to use any project property to configure any aspect of a plugin by embedding a reference to the project property in the configuration section for the plugin in the pom.xml.

This inconsistency means that the s3 key of the uploaded artifact is not automatically used by the LibraryMojo.   If I specify a plugin configuration item for "key", it should also be used by the LibraryMojo to install it.  Btw I need to do this as my artifact is a shaded jar and not the project artifact itself.

Unless I'm misunderstanding something (very possible!), I would remove the use of the databricks.repo project property and also have the LibraryMojo use the same s3 path as the UploadMojo

**Comment by samshuster** [comment]
Thanks for the write up. If I am understanding correctly, your idea is to get rid of databricks.repo in favor of using the "bucketName" and "key" properties instead.  

I will start working on this today and fix/clarify the README appropriately as well.

**Comment by daragallagher** [comment]
Hi Sam.  Thanks for responding so quickly.  Yeah that’s pretty much it exactly.   If I can help in any way, please let me know.  Cheers! Dara.

**Comment by daragallagher** [comment]
Great!
