### ISSUE TITLE
company prefix should not be hard coded

### ISSUE THREAD

**Issue by javamonkey79** [edmunds/databricks-maven-plugin#21]
The [COMPANY_GROUP_PREFIX](https://github.com/edmunds/databricks-maven-plugin/blob/master/src/main/java/com/edmunds/tools/databricks/maven/model/JobTemplateModel.java#L32) is hard coded to edmunds and should be instead configurable, defaulting to it's current setting.

**Comment by samshuster** [comment]
Hmm... this actually might not be a good first issue as I think this will require changing how we use the JobTemplateModel. In general, it seems we want to stay away from project.properties and use goal based configurations instead. This probably means that JobTemplateModel should no longer take a MavenProject but instead take explicit parameters (including "companyGroupPrefix")

**Comment by javamonkey79** [comment]
This is implemented.
