### ISSUE TITLE
Feature request: make restarting running clusters optional after library installation?

### ISSUE THREAD

**Issue by daragallagher** [edmunds/databricks-maven-plugin#23]
We would like to use the plug-in as part of the deploy stage of our build/CI process to install/update a Jar as a databricks library.  Since builds can happen at anytime (triggered by a git commit), for the users this would mean seemingly random cluster restarts, potentially losing lots of intermediate data/work and so (understantably IMHO) the idea has been rejected by the users.  

If the restart could be made optional via a plugin configuration item, this would be great.  We already have a notification system to tell all users that a new version has been deployed.  Users could then restart whenever it suits them and pick up the latest version after the restart.

I realize I've been requesting a lot over the last 2 days: 2 issues for databrick-maven-plugin and one issue for databricks-rest-client.  But I'm really keen to integrate our CD/CI process with databricks and these libraries provide 98% of what I need.  So I'm happy to help out and submit a pull request for this feature if it would be helpful?

Regards! Dara.

**Comment by daragallagher** [comment]
Hi Sam.  That's pretty much what I was thinking in terms of implementation.  I think it's pretty straightforward coding-wise and it will be easy to follow the existing style so I'll give it a go to submit a PR.  Cheers! Dara.

**Comment by samshuster** [comment]
hey @daragallagher! Just letting you know that I have some bandwidth to work on this today. I hope I am starting it before you started working on the PR. Apologies if this is not the case. I will add you as a reviewer.

**Comment by daragallagher** [comment]
Hey Sam.  Thanks that's great.  I had been struggling to find time to work on it.  And when I started I got sidetracked by the maven-plugin-testing-harness.  Cheers! Dara.
