### ISSUE TITLE
Uploading artefacts directly to DBFS

### ISSUE THREAD

**Issue by minikill** [edmunds/databricks-maven-plugin#68]
**Goal**
Add functional for uploading artifacts directly to DBFS

**Motivation**
To make artifacts deployments platform-agnostic

**Pull Request**
#69

**Comment by samshuster** [comment]
hey @minikill apologies for the VERY late response to your PR and issue. We will review internally on why it took so long to get back to you and come up with a plan on how to make sure that turn around times in the future are better. Thanks for your contribution!

We will take a look at your PR soon and see if we can get it merged in!
