### ISSUE TITLE
Maven Plugin should not force a jar to be attached

### ISSUE THREAD

**Issue by samshuster** [edmunds/databricks-maven-plugin#9]
# Overview
I found out that the plugin forces the job description to have the project jar attached as a library.

For this project, it doesn’t make sense for this to be the case.

# Acceptance Criteria
- It is possible to have jobs that don't require a jar

One possible way of doing this could be to be able to override the libraries section in the job settings file. Or perhaps it is a flag?

**Comment by Mikhail-Ivanov** [comment]
Seems to be resolved with that PR: https://github.com/edmunds/databricks-maven-plugin/pull/58

**Comment by javamonkey79** [comment]
Nice find @Mikhail-Ivanov , you're right.
